[package]
name = "geo-proc"
version = "0.1.0"
authors = ["Asger Nyman Christiansen <asgernyman@gmail.com>"]
edition = "2018"

[dependencies]
tri-mesh = {git = "https://github.com/asny/tri-mesh"}
tobj = "0.1.6"
