[package]
name = "geo-proc"
version = "0.1.0"
authors = ["Asger Nyman Christiansen <asgernyman@gmail.com>"]
edition = "2018"

[dependencies]
tri-mesh = "0.1.2"
tobj = "0.1.6"

[dev-dependencies]
dust = { git = "https://github.com/asny/Dust", branch="WebGL" }