[package]
name = "gust_example"
version = "0.1.0"
authors = ["Asger Nyman Christiansen <asgernyman@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
dust = { git = "https://github.com/asny/Dust"}
wasm-bindgen = "0.2.33"
serde_json = "1.0.33"
geo-proc = { path = "../../" }